name: Teste de Pull Request

on: [pull_request]

jobs:
  check-sobre-page:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v3

      # Verifica se o arquivo sobre.html existe
      - name: Verificar se sobre.html existe
        run: |
          if [ -f "sobre.html" ]; then
            echo "Teste passou: 'sobre.html' encontrado."
          else
            echo "Teste falhou: 'sobre.html' não encontrado."
            exit 1
          fi
